services:
  # Servicio de MySQL
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql  # Persistencia de datos en contenedor
    networks:
      - dev-network
    restart: always

  # Servicio de Nginx (servidor web)
  web:
    image: nginx:latest
    container_name: nginx-serverjenkins3
    ports:
      - "${WEB_SERVER_PORT}:80"  # Mapea el puerto en el host
    volumes:
      - ./public:/usr/share/nginx/html  # Carpeta local con los archivos estáticos
      - ./nginx.conf:/etc/nginx/nginx.conf  # Si tienes un archivo de configuración personalizado
    networks:
      - dev-network
    depends_on:
      - mysql  # Asegura que el servicio MySQL esté disponible antes de iniciar Nginx
    restart: always

networks:
  dev-network:
    driver: bridge  # Red interna para comunicación entre contenedores

volumes:
  mysql-data:
    driver: local  # Almacena los datos persistentes de MySQL